name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: database
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Wait for Postgres to be ready
    #   run: |
    #     until curl -s --connect-timeout 5 postgres:5432; do
    #       echo "Waiting for Postgres to be ready..."
    #       sleep 5
    #     done

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check linting
      run: |
        pip install flake8
        flake8 .

    - name: Run tests
      run: |
        pip install pytest
        cp .env.sample .env
        export POSTGRES_HOST=postgres
        export POSTGRES_TEST_PORT=5433
        pytest
